<a href="https://colab.research.google.com/github/bhumibansal-ux/Bhumi1/blob/main/api_to_dataframeipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,982843,The Great Flood,When a raging flood traps a researcher and her...,2025-09-18,14.9627,5.996,643
1,55465,A Very Harold & Kumar Christmas,"Six years have elapsed since Guantanamo Bay, l...",2011-11-04,1.9699,6.000,1047
2,11133,Poltergeist II: The Other Side,The Freeling family move in with Diane's mothe...,1986-05-23,1.6494,6.000,749
3,9645,Ghost Ship,After discovering a passenger ship missing sin...,2002-10-25,3.8853,5.995,2620
4,8555,Creep,"Trapped in a London subway station, a woman wh...",2004-08-10,1.8237,6.000,829

In [ ]:
df = pd.DataFrame()

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
all_movie_dfs = []
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    all_movie_dfs.append(temp_df)
df = pd.concat(all_movie_dfs, ignore_index=True)

In [ ]:
df.shape

(8560, 7)

In [ ]:
df.to_csv('movies.csv')